name: Deploy WordPress Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add host to known_hosts
        run: |
          ssh-keyscan -H 49u.3f0.myftpupload.com >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=yes \
          git_deployer_81fab9972a_541212@49u.3f0.myftpupload.com "pwd && ls -la"

      - name: Deploy site
        run: |
          rsync -rvz \
            --omit-dir-times \
            --no-perms \
            --no-owner \
            --no-group \
            --exclude ".git" \
            --exclude ".github" \
            -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=yes" \
            ./ \
            git_deployer_81fab9972a_541212@49u.3f0.myftpupload.com:/
